//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nauczyciele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nauczyciele()
        {
            this.Wycieczkis = new HashSet<Wycieczki>();
            this.ZadaniaDomowes = new HashSet<ZadaniaDomowe>();
        }
    
        public int ID { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public int PrzedmiotID { get; set; }
    
        public virtual Przedmioty Przedmioty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wycieczki> Wycieczkis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZadaniaDomowe> ZadaniaDomowes { get; set; }
    }
}
