//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wycieczki
    {
        public int ID { get; set; }
        public Nullable<int> KlasaID { get; set; }
        public Nullable<int> NauczycielID { get; set; }
        public string Miasto { get; set; }
        public string Atrakcje { get; set; }
        public Nullable<System.DateTime> Od { get; set; }
        public Nullable<System.DateTime> Do { get; set; }
    
        public virtual Klasy Klasy { get; set; }
        public virtual Nauczyciele Nauczyciele { get; set; }
    }
}
